[package]
name = "test_web"
version = "0.1.0"
authors = ["Yoshihiko Yamanaka <bamchoh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
tera = "1.8"
serde = "1.0"
serde_derive = "1.0"
